### ISSUE TITLE
Unexpected timeout behavior with default settings (related to timeout_trigger)

### ISSUE THREAD

**Issue by Deimos** [jvanasco/pyramid_session_redis#11] opened 2018-05-28 02:51 UTC
Hey @jvanasco,

I've been using pyramid_session_redis in a "production" site for a couple of weeks now and it's been working well - the traffic isn't anything insane, but a few hundred active users anyway. However, there's been some complaints about inconsistent session timeouts - some users are staying logged in, but others have had their sessions seem to randomly drop out, and then one will eventually just seem to "stick" properly for no apparent reason.

I think I've figured out the cause now, and it's very possible that I'm just doing things in a weird/wrong way, but it may also indicate a bug or some unexpected behavior with pyramid_session_redis, so I wanted to post it here for you.

First of all, my settings are pretty basic, I set:

```
redis.sessions.secret = <removed>
redis.sessions.unix_socket_path = /run/redis/socket
redis.sessions.prefix = session:
redis.sessions.cookie_secure = true
redis.sessions.cookie_max_age = 31536000
redis.sessions.timeout = 3600
```

I start with the default timeout for a session set to an hour, and extend it using `request.session.adjust_timeout_for_session()` when a user logs in - this is to make it so that logged-out sessions get dropped out of redis relatively quickly.

Here's the unexpected behavior that I'm seeing:

1. A user comes to the site without a session, so they're not logged in and a new session is created for them in redis, with timeout 3600 seconds.
2. They log in, and I use `adjust_timeout_for_session()` to set their timeout to either 1 day or 1 year, depending if they checked the "keep me logged in" box or not.
3. If I examine the actual session data stored in redis at this point, the TTL on the redis key has been updated to the correct value (86400 or 31536000), but **the `x` value stored inside the python dict is still 3600, and the `t` value is still the original 1-hour-later timestamp**.
4. Now, because of the default `timeout_trigger` setting of 600, my understanding is that the `x` and `t` values are only going to get updated if the user is active on the site within 10 minutes of the session expiry (50 minutes after the session was originally created). So if they use the site for half an hour and then leave for a couple hours, when they come back, their session will be expired and they'll be logged out.

Is this correct, or am I misunderstanding something? It doesn't seem like this would be desired behavior, where the user must be active within 10 minutes of their session expiring or it won't properly refresh.

**Comment by jvanasco** [comment] 2018-05-28 03:34
> but the x value stored inside the python dict is still 3600, and the t value is still the original 1-hour-later timestamp.

This sounds like a bug.  Thanks for reaching out!  I don't think I have a unit-test covering that scenario, and this package should.  I'm going to dig into this over the next few days.

I haven't personally seen this pop up, because I use a cookie with an encrypted payload to handle the "keep me logged in" option.  I'm bringing this up because, while it does sound like you found a bug I need to fix, the way Redis can make space for new data by removing stale data, can cause the sticky login to fail over time.

**Comment by Deimos** [comment] 2018-05-28 04:11
I think what I consider the main strange behavior might have gotten distracted from a bit too with me bringing in the timeout update on login and such, let me try giving a simpler case:

Imagine a very simple usage - sessions that always expire after 1 hour. With the default `timeout_trigger` of 600, does that mean that the session will only refresh if it's used within the last 10 minutes before it expires? If the user uses the site for 40 minutes, then is inactive for 30, then comes back, will the session be expired?

**Comment by jvanasco** [comment] 2018-05-28 05:05
No worries.  Thanks for bringing this up, there are some issues here.

>  If the user uses the site for 40 minutes, then is inactive for 30, then comes back, will the session be expired?

Yes. If sessions are set for a 1hour expiry and a 10minute trigger, it would invalidate.  In your situation, you'd either want no timeout trigger OR adjusting it to suit your needs.

Bear with me while I try to explain this - it is needlessly overcomplicated and this behavior isn't actually half-assed (though it may seem that way).

For the sake of clarity, I'll use an oversimplification that Redis essentially has two different internal data stores that are used independently: one for a Key's payload and another for the Key's expiry.

In the 'classic' behavior (project this was forked from): every time you access an existing session, the `GET` is followed by sending Redis a new `EXPIRE` time – essentially every "read" has a corresponding "write" for the Redis-tracked expiry record. 

In order to minimize the writes via SETEX, I introduced the timeout trigger.  The trigger works by storing some timeout information in the Redis data payload, and using that information to determine when to send a write.  Instead of having a `GET`+`EXPIRE` for every read, we only have a single `GET` and eliminate the write caused by the `EXPIRE`. This has a maintenance cost though - once we hit the timeout trigger, instead of just the `GET` we need to update the internal timeout payload and issue a `SET`.

Going back to your situation: when the user stops activity at 40 minutes in, if the timeout trigger is enabled then there has never been an update to the internal payload or Redis about the user activity since the session was first created.  The purpose of the trigger is to defer that "write" operation.   

In order to make a session valid for "reading" for around an hour, you'd want to do something like:

* a two-hour session with a 10 minute trigger, or
* a one-hour session with a 50 minute trigger

You can also disable the functionality by setting the trigger to 0.  Up to a few thousand daily users, you shouldn't have any issues with the overhead of the "classic" mode.  When you hit 10k users and/or start to have clustered web servers communicating with dedicated Redis instances, setting a new `EXPIRE` after every read operation becomes something you want to avoid.

**Comment by Deimos** [comment] 2018-05-28 05:31
Thanks for explaining, it seems like I had it correct then.

I think that's *extremely* unexpected default behavior for the library, and it gets worse the longer of a session you set up (or think you're setting up). If I set `redis.sessions.timeout = 86400`, I expect that my sessions will expire when they're unused for 24 hours. I don't expect them to expire "24 hours after they were started, unless they're used between 23:50:00 and 23:59:59". This seems like it's appropriate for a very specialized use case that should need to be enabled specifically, not the default.

I'm not sure if there are many other people using this library over the original, but at least in my case I definitely wasn't expecting this behavior, and probably spent about half a day today trying to figure out what was going wrong because it didn't make any sense to me. It's also not explained very well in the README - there's no indication that it's enabled (and set to 600) by default, or that you need to set it to `0` to disable this behavior, I only found those out from the code.

I hope I'm not coming off as ungrateful - I definitely appreciate that you're working on this fork and I know you've made a lot of improvements over the original, I just think that this particular behavior shouldn't be on by default.

On a different note, have you tried using a [Redis pipeline](https://redis.io/topics/pipelining) for the `GET`/`EXPIRE` calls? Or does that not help with the overhead from them?

**Comment by jvanasco** [comment] 2018-05-28 06:03
that's a good point. i'll make a note to swap it out of being default and make the docs more clear about this.

unfortunately, pipeline doesn't really help this situation. it does help a tiny bit, but with only 2 items in the pipeline it's there's not much overhead to save from the context switching, and there is still all the cumulative writes, the bottleneck is simply having Redis handling any writes at all.  

but... I could introduce a config option to implement reads via an initial pipelined GET+EXPIRE, then mark the session to not EXPIRE via a deferred refresh.  The original package did a refresh and/or set on every attribute access (which was killing our systems); I initially forked it to defer the write actions into a single deferred callback action.  this is worth looking into.

**Comment by jvanasco** [comment] 2018-05-28 19:55
thanks. still trying to build out a testcase for what you described above.  almost there, i think...

**Comment by jvanasco** [comment] 2018-05-29 02:39
Ok.

i can't seem to recreate this error. All the tests I've made are passing.  If you have time and can replicate it, that would be great.

the `master` now has a release candidate that will automagically pipeline a get+expire on reads, and suppress the 'expire' at cleanup if the following is configured

* there is a timeout
* there is no timeout_trigger
* there is no python_expires
* redis tracks ttl

**Comment by Deimos** [comment] 2018-05-29 04:56
Sorry, which error are you trying to recreate? The `x` and `t` values not updating?

**Comment by jvanasco** [comment] 2018-05-29 04:59
Yes. I haven't been able to update the TTL in redis while not updating the time data in the python payload.

**Comment by jvanasco** [comment] 2018-05-29 20:09
after a bit of testing and test refactoring, i found a few cases where the TTL wouldn't set in redis. that's now been fixed in `master`.

I also made the above redis optimization feature off by default, and requiring an explicit opt-in of `set_redis_ttl_readheavy=True`.  It still requires the same criteria, and will raise a ValueError on factory configuration if unsupported.

**Closed** 2019-09-18 19:33 UTC
